version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio
    container_name: portfolio
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app